print("----------------------------------")
car2.pick(user2, user3)
print("----------------------------------")
car3.pick(user3)
print("----------------------------------")
user2.status()
user3.status()